[workspace]
members = [
    "zinc64",
    "zinc64-core",
    "zinc64-debug",
    "zinc64-loader",
    "zinc64-system"
]
default-members = [
    "zinc64-core",
    "zinc64-debug",
    "zinc64-loader",
    "zinc64-system",
    "zinc64"
]


